# Generated by Django 3.0.3 on 2020-02-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itemID', models.CharField(max_length=50)),
                ('seralID', models.CharField(max_length=50)),
                ('description', models.CharField(default='none', max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slots', models.IntegerField(default=0)),
                ('occSlot', models.IntegerField(default=0)),
                ('description', models.CharField(default='none', max_length=500)),
            ],
        ),
    ]
