# Generated by Django 3.0.3 on 2020-02-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200224_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsOnRack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('rack', models.CharField(default='*', max_length=500)),
            ],
        ),
    ]
