# Generated by Django 3.0.4 on 2020-03-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_itemsonrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rack',
            field=models.CharField(default='o', max_length=500),
        ),
    ]
